busucrm/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace="leads")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import (lead_delete, PerfilView, PerfilDetailView, gerenciar,
                    robos_list, lead_detail, create_robo, lead_update, robo_update, robo_delete, carrinho, OrderSummaryView, remove_single_item_from_cart, remove_from_cart, Pagamento)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "leads"

urlpatterns = [
    path('', robos_list, name='lead-list'),
    path('<int:pk>/', lead_detail, name='lead-detail'),
    path('<int:pk>/delete/', lead_delete, name='lead-delete'),
    path('<int:pk>/deleterob/', robo_delete, name='robo-delete'),
    path('criar/', create_robo, name='criar-robos'),
    path('mercado/', robos_list, name='mercado'),
    path('adicionar-ao-carrinho/<slug>/', carrinho, name='add-to-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart,
         name='remove-from-cart'),
    path('carrinho/', OrderSummaryView.as_view(), name='order-summary'),
    path('gerenciar/', gerenciar, name='gerenciar-robos'),
    path('perfil/', PerfilView, name='perfil-view'),
    path('<int:pk>/update/', lead_update, name='perfil-update'),
    path('<int:pk>/updaterob/', robo_update, name='robo-update'),
    path('<int:pk>/perfil/', PerfilDetailView.as_view(), name='perfil-detail'),
    path('pagamento/<int:pk>', Pagamento.as_view(), name='pagamento'),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField, UserChangeForm
from .models import Robos, User

User = get_user_model()


class RobosForm(forms.ModelForm):
    class Meta:
        model = Robos
        fields = (
            'nome',
            'descricao',
            'robocode',
            'robopic',
            'preco',
        )
    def __init__(self, *args, **kwargs):
        super(RobosForm, self).__init__(*args, **kwargs)
        self.fields['descricao'].label = "Descrição"
        self.fields['robocode'].label = "Código (Formatos: .py, .js etc...)"
        self.fields['robopic'].label = "Imagem do robô"
        self.fields['preco'].label = "Preço"



class ProfileForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = {"username", "email", "descricao_user",
                  "profilepic", "comentario", }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = {"username", "email", "descricao_user",
                  "profilepic", "comentario", }
        field_classes = {"username": UsernameField}

leads/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.views import generic
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.views.generic.base import View
from .models import Carrinho, OrderItem, Robos, User
from django.db.models import F
from .forms import RobosForm, CustomUserCreationForm, ProfileForm
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage
from django.utils import timezone
import requests
import random
import json
import datetime

class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")


class LandingPageView(TemplateView):
   
    template_name = "landing.html"

def svgecor(retorno):
        if retorno == False:
            robos = Robos.objects.all()
            svgecor.svg, svgecor.cor = [], []
            for i in range(len(robos)):
                l = i * 2
                j = - i - i
                strfy = ' ' + str(l)
                strfy2 = ' ' + str(l - i - i)
                dummy = ('M'+  str(l) +  strfy2  + strfy + strfy2)
                first = ''
                r = lambda: random.randint(0,255)
                cores = '#%02X%02X%02X' % (r(),r(),r())
                if svgecor.svg == []:
                    svgecor.svg.append(first)
                    svgecor.cor.append(cores)
                if i > 0:
                    svgecor.svg.append(dummy + ' ' + svgecor.svg[i-1])
                    svgecor.cor.append(cores)


def robos_list(request):
    robos = Robos.objects.all()
    p = Paginator(robos, 8)
    page_num = request.GET.get('page', 1)
    try:
        page = p.page(page_num)
    except EmptyPage:
        page * p.page(1)

    svgecor(False)
    svg = svgecor.svg
    cor = svgecor.cor  
    context = {
        "robos": page,
        "svg": svg,
        "cor": cor
    }
    return render(request, "leads/lead_list.html", context)


def lead_detail(request, pk):
    robos = Robos.objects.get(id=pk)
    if request.user.is_authenticated:
        order_qs = Carrinho.objects.filter(user=request.user)
        for i in order_qs:
            if i.ordered == True:
                for x in i.items.all():
                    if x.item == robos:
                        order = True
                    else:
                        order = False
            else:
                order = False
    else:
        order = False

    contador = Robos.objects.all().count()
    i = 1

    while i < 3:
        recom1 = Robos.objects.order_by('?')[0]
        recom2 = Robos.objects.order_by('?')[0]
        recom3 = Robos.objects.order_by('?')[0]
        recom4 = Robos.objects.order_by('?')[0]
        recom5 = Robos.objects.order_by('?')[0]
        recom6 = Robos.objects.order_by('?')[0]

        list1 = set([recom1.nome, recom2.nome, recom3.nome])
        list2 = set([recom4.nome, recom5.nome, recom6.nome])

        c = bool(list1.intersection(list2))

        if contador < 6:
            i = 4
        elif c == True or len(list1) < 3 or len(list2) < 3:
            i = 2
        else:
            i = 4

    list = []
    if robos.reviews != None:
        for i in range(0, robos.reviews):
            list.append(i)

    svg=request.POST.get("svg", "")
    cor=request.POST.get("cor", "")
    svgecor(False)
    svgdummy = svgecor.svg
    cordummy = svgecor.cor

    if svg == "":
        svg = svgdummy[random.randrange(0, contador)]
        cor = cordummy[1]

    context = {
        "robos": robos,
        "order": order,
        "recom1": recom1,
        "recom2": recom2,
        "recom3": recom3,
        "recom4": recom4,
        "recom5": recom5,
        "recom6": recom6,
        "list": list,
        "svg": svg,
        "cor": cor,
        "svgdummy": svgdummy,
        "cordummy": cordummy,
    }
    return render(request, "leads/lead_detail.html", context)


def carrinho(request, slug):
    item = get_object_or_404(Robos, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )   
    order_qs = Carrinho.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]

        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantidade += 0
            order_item.save()
            return redirect("leads:order-summary")
        else:
            order.items.add(order_item)
            messages.info(request, "Adicionado ao carrinho.")
            return redirect("leads:order-summary")
    else:
        ordered_date = timezone.now()
        order = Carrinho.objects.create(
            user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "Adicionado ao carrinho.")
        return redirect("leads:order-summary")


def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Robos, slug=slug)
    order_qs = Carrinho.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantidade > 1:
                order_item.quantidade -= 1
                order_item.save()
            else:
                order_item.delete()
                messages.info(request, "Você está sem itens no carrinho")
                return redirect("leads/lead_list")
        else:
            messages.info(request, "Isso não estava no seu carrinho")
            return redirect("leads/lead_list.html")
    else:
        messages.info(request, "Você não tem nenhum item no carrinho")
        return redirect("leads/lead_list.html")


def remove_from_cart(request, slug):
    item = get_object_or_404(Robos, slug=slug)
    order_qs = Carrinho.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "Removido do carrinho.")
            return redirect("leads:order-summary")
        else:
            messages.info(request, "Este produto não está no seu carrinho.")
            return redirect("leads/lead_list.html")
    else:
        messages.info(request, "Você não tem um carrinho.")
        return redirect("leads/lead_list.html")


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Carrinho.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            thereisobject = Carrinho.objects.filter(user=self.request.user, ordered=False)
            for i in thereisobject:
                if i.ordered == False:
                    if len(i.items.all()) < 1:
                        messages.warning(
                            self.request, "Você não tem nenhum item no carrinho.")
                        return redirect("../../leads/mercado/")
          

            return render(self.request, 'leads/carrinho.html', context)
        except ObjectDoesNotExist:
            messages.warning(
                self.request, "Você não tem nenhum item no carrinho.")
            return redirect("../../leads/mercado/")

class Pagamento(LoginRequiredMixin, View):
   def get(self, *args, **kwargs):
        try:
            '''
            order = Carrinho.objects.get(user=self.request.user, ordered=False)
            order_id = order.id
            print(order_id)
            total_limpo = order.get_total()
            total_nraw = f'{total_limpo:.30f}'
            print(total_nraw)
            data = {"callback": f"http://127.0.0.1:8000/leads/pagamento/{order.id}","amount": total_nraw}
            headers = {"Content-Type": "application/json"}
            url = "http://127.0.0.1:13380/sales"
            response = requests.post(url, headers=headers, json=data) 
            body = response.json()
            qr = body.get('url')
            print(qr)
            pago = body.get('paid')
            print(pago)
            context = {
                'valor': total_limpo,
                'pago': pago,
                'qr': qr,
                'order': order_id
            } 

            return render(self.request, 'leads/pagamento.html', context)
            '''
            
            order = Carrinho.objects.get(user=self.request.user, ordered=False)
            for orders in order.items.all():
                orders.ordered = True
            order.ordered = True
            order.save()
            context = {
                'qr': 'teste',
                'pago': 'Está pago (Funcionalidade não ativa nesse site).'
            }
            return render(self.request, 'leads/pagamento.html', context)

            return redirect("../../leads/mercado/")
            

        except ObjectDoesNotExist:
            messages.warning(
                self.request, "Você não tem nenhum item no carrinho.")
            return redirect("/")

leads/templates/leads/carrinho.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="flex justify-center my-6 py-24 shadow-xl">
    <div class="flex flex-col w-full p-8 text-gray-800 bg-white shadow-xl pin-r pin-y md:w-4/5 lg:w-4/5">
      <div class="flex-1">
        <table class="w-full text-sm lg:text-base" cellspacing="0">
          <thead>
            <tr class="h-12 uppercase">
              <th class="hidden md:table-cell"></th>
              <th class="text-left">Item</th>
              <th class="lg:text-right text-left pl-5 lg:pl-0">
                <span class="hidden lg:inline">Quantidade</span>
              </th>
              <th class="hidden text-right md:table-cell">Preço unitário</th>
              <th class="text-right">Total</th>
            </tr>
          </thead>
          <tbody>
            {% load static %}
            {% for order_item in object.items.all %}
            <tr class="bg-gray-100">
              <tr class="border-gray-300 border-2"></tr>
              <td class="hidden pb-4 md:table-cell py-4">
                <a href="{% url 'leads:lead-detail' order_item.item.pk%}">
                  {% if order_item.item.robopic == '' %}
                  <svg xmlns="http://www.w3.org/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" class="object-cover object-center w-20 rounded h-14 text-white" style="background-color: #67EF;" viewBox="-8 0 40 20">
                    <path d="M12 2L2 7l10 5 10-5-10-5zM-0 0-0 0 0-0M2 12l10 5 10-5 {{ svg }}"></path>
                  </svg>
                  {% else %}
                  <img src="/media/{{ order_item.item.robopic }}" class="w-20 rounded" alt="Thumbnail">
                  {% endif %}
                </a>
              </td>
              <td>
                <a href="{% url 'leads:lead-detail' order_item.item.pk%}">
                  <p class="hover:text-blue-600 font-semibold mb-2 md:ml-4">{{ order_item.item.nome }}</p></a>
                    <a type="submit" href="{% url 'leads:remove-from-cart' order_item.item.slug %}" class="hover:text-red-700 text-gray-700 md:ml-4 text-lg">
                      <small>Remover</small>
                    </a>
                
              </td>
              <td class="justify-center md:justify-end md:flex mt-6">
                <div class="w-20 h-10">
                  <div class="relative flex flex-row w-full h-8">
                    <input readonly value="{{ order_item.quantidade }}" 
                    class="w-full h-full font-semibold text-center text-gray-700 bg-gray-100 outline-none focus:outline-none hover:text-black focus:text-black" />
                  </div>
                </div>
              </td>
              <td class="hidden text-right md:table-cell">
                <span class="text-sm lg:text-base font-medium">
                  Ӿ {{ order_item.item.preco }}
                </span>
              </td>
              <td class="text-right">
                <span class="text-sm lg:text-base font-medium">
                  Ӿ {{ order_item.get_total_item_price }}
                </span>
              </td>
              <tr class="border-gray-300 border-2"></tr>
            </tr> 
            {% endfor %}

          </tbody>
        </table>
        <hr class="pb-6 mt-6">
        <div class="my-4 mt-6 -mx-2 lg:flex">
          <div class="lg:px-2 lg:w-1/2">
            <div class="p-4 bg-gray-100 rounded-full">
              <h1 class="ml-2 font-bold uppercase">CUPOM</h1>
            </div>
            <div class="p-4">
              <p class="mb-4 p-4 italic">Se você tem um código de promoção coloque aqui</p>
              <div class="justify-center md:flex">
                    <div class="flex items-center w-full h-13 pl-3 bg-white bg-gray-100 border rounded-full">
                      <input type="coupon" name="code" id="coupon" placeholder="SEUCUPOMAQUI" value="SEUCUPOMAQUI"
                              class="w-full bg-gray-100 outline-none appearance-none focus:outline-none active:outline-none"/>
                        <button class="text-sm flex items-center px-3 py-1 text-white bg-blue-600 rounded-full outline-none md:px-4 hover:bg-blue-700 focus:outline-none active:outline-none">
                          <svg aria-hidden="true" data-prefix="fas" data-icon="gift" class="w-8" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M32 448c0 17.7 14.3 32 32 32h160V320H32v128zm256 32h160c17.7 0 32-14.3 32-32V320H288v160zm192-320h-42.1c6.2-12.1 10.1-25.5 10.1-40 0-48.5-39.5-88-88-88-41.6 0-68.5 21.3-103 68.3-34.5-47-61.4-68.3-103-68.3-48.5 0-88 39.5-88 88 0 14.5 3.8 27.9 10.1 40H32c-17.7 0-32 14.3-32 32v80c0 8.8 7.2 16 16 16h480c8.8 0 16-7.2 16-16v-80c0-17.7-14.3-32-32-32zm-326.1 0c-22.1 0-40-17.9-40-40s17.9-40 40-40c19.9 0 34.6 3.3 86.1 80h-86.1zm206.1 0h-86.1c51.4-76.5 65.7-80 86.1-80 22.1 0 40 17.9 40 40s-17.9 40-40 40z"/></svg>
                          <span class="font-medium ml-2"> APLICAR</span>
                        </button>
                    </div>
              </div>
            </div>
          </div>
          <div class="lg:px-2 lg:w-1/2">
            <div class="p-4">
                <div class="flex justify-between border-b">
                  <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                    Subtotal
                  </div>
                  <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                    Ӿ {{ object.get_total }} 
                  </div>
                </div>
                  <div class="flex justify-between pt-4 border-b">
                    <div class="flex lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-gray-800">
                        <a href="" class="mr-2 mt-2 lg:mt-2">
                          <svg aria-hidden="true" data-prefix="far" data-icon="trash-alt" class="w-4 text-red-600 hover:text-red-800" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M268 416h24a12 12 0 0012-12V188a12 12 0 00-12-12h-24a12 12 0 00-12 12v216a12 12 0 0012 12zM432 80h-82.41l-34-56.7A48 48 0 00274.41 0H173.59a48 48 0 00-41.16 23.3L98.41 80H16A16 16 0 000 96v16a16 16 0 0016 16h16v336a48 48 0 0048 48h288a48 48 0 0048-48V128h16a16 16 0 0016-16V96a16 16 0 00-16-16zM171.84 50.91A6 6 0 01177 48h94a6 6 0 015.15 2.91L293.61 80H154.39zM368 464H80V128h288zm-212-48h24a12 12 0 0012-12V188a12 12 0 00-12-12h-24a12 12 0 00-12 12v216a12 12 0 0012 12z"/></svg>
                        </a>
                      CUPOM 
                    </div>
                    <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-green-600">
                      Ӿ 0 
                    </div>
                  </div>
                  <div class="flex justify-between pt-4 border-b">
                    <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                      Total
                    </div>
                    <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-green-700">
                      Ӿ {{ object.get_total }}
                    </div>
                  </div>
                <a href="{% url 'leads:pagamento' object.id %}">
                  <button class="flex justify-center w-full px-10 py-3 mt-6 font-medium text-white uppercase bg-blue-600 rounded-full shadow item-center hover:bg-blue-700 focus:shadow-outline focus:outline-none">
                    <svg class="w-12 h-12 mr-20 " viewBox="0 0 1080 1080" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <circle cx="540" cy="540" r="540" fill="white"/>
                      <path d="M792.911 881H740.396L541.099 570.561L338.761 881H286.68L513.452 529.3L306.882 206.222H360.42L541.95 490.393L727.322 206.222H777.555L568.762 528.379L792.911 881Z" fill="#209CE9"/>
                      <path d="M336.487 508.737H744.807V547.116H336.487V508.737ZM336.487 623.872H744.824V662.251H336.47L336.487 623.872Z" fill="#209CE9"/>
                      </svg>
                    <span class="mr-20 mt-2 mb-3"><p class="text-xl font-semibold">Finalizar</p></span>
                  </button>
                </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %} {% block content %} {% load market_tags %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap -m-4">    
      {% for robo in robos %}

      <div class="lg:w-1/4 md:w-1/2 p-6 space-x-1 w-full shadow-md">
                 
        <form action="{% url 'leads:lead-detail' robo.pk %}" method="post" id="{{ forloop.counter0 }}">
        {% csrf_token %}
        
          {% if robo.robopic == '' %} {% load static %}<input type="hidden" name="cor" value="{{ cor|index:forloop.counter0 }}"><input type="hidden" name="svg" value="{{ svg|index:forloop.counter0 }}"><a
          type="submit"
          class="block relative h-52 w-full rounded overflow-hidden"
          href="javascript:$('#{{ forloop.counter0 }}').submit()"
        ></form>
          <svg xmlns="http://www.w3.org/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" class="object-cover object-center w-full h-full block text-white" style="background-color: {{ cor|index:forloop.counter0 }};" viewBox="-8 0 40 20">
            <path d="M12 2L2 7l10 5 10-5-10-5zM-0 0-0 0 0-0M2 12l10 5 10-5 {{ svg|index:forloop.counter0 }}"></path>
          </svg> {% else %}
          <a
          class="block relative h-52 w-full rounded overflow-hidden"
          href="{% url 'leads:lead-detail' robo.pk %}"
        >
          <img
            alt="robo"
            class="object-cover object-center w-full h-full block"
            src="/media/{{ robo.robopic|default_if_none:'semfoto.png' }}"
          />
          {% endif %}
        </a>

        <div class="mt-4">
          <a href="{% url 'leads:perfil-detail' robo.usuario.pk %}"
            ><h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">
              {{ robo.usuario }}</a> | {{ robo.data }}
            </h3>
          
          <a href="{% url 'leads:lead-detail' robo.pk %}"
            ><h2 class="text-gray-900 title-font text-lg font-medium mb-1">
              {{ robo.nome }}
            </h2></a
          >
          {% if robo.preco == None %}
          <a href="{% url 'leads:lead-detail' robo.pk %}"
            ><p class="mt-1">A definir valor.</p></a
          >
          {% else %}
          <a href="{% url 'leads:lead-detail' robo.pk %}"
            ><svg class="inline-flex" id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1730 760.9" width="35" height="15"><style>.st0{fill:#4a90e2}</style><circle class="st0" cx="124.5" cy="625.3" r="124.5"/><path class="st0" d="M1608.1 8c-67.4 0-124.5 54.5-124.5 124.5 0 98.6-15.6 124.5-124.5 124.5h-10.4c-62.2 5.2-111.5 57.1-111.5 121.9v2.6c0 96-18.2 119.3-124.5 119.3-5.2 0-10.4 0-13 2.6-62.2 7.8-111.5 59.7-111.5 121.9 0 67.4 54.5 124.5 124.5 124.5 64.8 0 119.3-51.9 121.9-114.1v-10.4c0-88.2 28.5-121.9 121.9-124.5h2.6c64.8 0 119.3-51.9 121.9-116.7v-7.8c0-90.8 28.5-124.5 124.5-124.5 67.4 0 124.5-54.5 124.5-124.5C1730 62.5 1675.5 8 1608.1 8zM876.7 257h-10.4c-108.9 0-124.5-25.9-124.5-124.5C741.8 65.1 687.3 8 617.3 8c-67.4 0-124.5 54.5-124.5 124.5 0 98.6-15.6 121.9-124.5 121.9h-10.4c-62.2 5.2-111.5 57.1-111.5 121.9 0 67.4 54.5 124.5 124.5 124.5 64.8 0 119.3-51.9 121.9-114.1v-7.8c0-90.8 28.5-124.5 124.5-124.5s124.5 33.7 124.5 121.9c0 67.4 54.5 124.5 124.5 124.5s124.5-54.5 124.5-124.5c-2.6-62.2-51.9-114.1-114.1-119.3z"/></svg></a><p class="inline ml-1 mt-1">{{ robo.preco }}</p><script>document.getElementById('botao').style.visibility='hidden';</script>
          {% endif %}
        </div>
      </div>

      {% endfor %}
    </div>
    <br /><br /><br />
    {% if robos.has_previous %}
    <a id="prev" href="?page={{robos.previous_page_number}}"
      ><p class="text-gray-900">Pagina anterior</p></a
    >
    {% endif %} {% if robos.has_next %}
    <a id="next" href="?page={{robos.next_page_number}}"href="javascript:$('form').submit()"
    ><p class="justify-end flex text-gray-900">Proxima página</p></a
    >
    {% endif %}
  </div>
</section>

{% endblock %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">CLIENTE</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.nome }} {{ lead.sobrenome }}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead-detail' lead.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Descrição</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Estatisticas</a>
          <a href="{% url 'leads:lead-update' lead.pk%}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Modificar</a>
        </div>
                <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Confirmar</button>
                </form>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
    <a href={% url 'leads:lead-delete' lead.pk %}>
    <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Deletar</button>
    </button>
    </a>
  </div>
  
</section>

{% endblock content %}